### PR TITLE
Allow user to specify DNS when setting static IP

### PR DESCRIPTION
**Pull request by AristoChen**
Hi, 

This PR is for #142, please let me know if I misunderstood anything or did anything wrong, thanks!

btw, I also found there are some other code in this file still using 8.8.8.8 as DNS([line 235](https://github.com/armbian/config/blob/master/debian-config-functions-network#L235), [line 413](https://github.com/armbian/config/blob/master/debian-config-functions-network#L413), [line 441](https://github.com/armbian/config/blob/master/debian-config-functions-network#L441)), is it supposed to be modified as well?

### CODE REVIEW

**Review by lanefu — APPROVED** [review]

**Comment by lanefu** [comment]
> Hi,
> 
> This PR is for #142, please let me know if I misunderstood anything or did anything wrong, thanks!
> 
> btw, I also found there are some other code in this file still using 8.8.8.8 as DNS([line 235](https://github.com/armbian/config/blob/master/debian-config-functions-network#L235), [line 413](https://github.com/armbian/config/blob/master/debian-config-functions-network#L413), [line 441](https://github.com/armbian/config/blob/master/debian-config-functions-network#L441)), is it supposed to be modified as well?

Yes looks like should be added for all

**Comment by AristoChen** [comment]
for function called `create_if_config`, it does not trigger a dialog for user to type anything, so I directly use `dns=$gateway`

for function called `systemd_ip_editor` and `ip_editor`, use the same way as `nm_ip_editor`

**Comment by lanefu** [comment]
@AristoChen sorry for the delay I didn't notice your updates earlier

**Comment by lanefu** [comment]
tested on buster looks good

**Pull request merged**
