### PR TITLE
Allow user to choose version of kernel to install or remove

### PR DESCRIPTION
**Pull request by AristoChen**
Hi, 

I was playing around with installing kernel, and I found that I can only install the latest version of kernel source, which is different from the version that I'm using currently, so I think that it might be a good thing to allow user to choose from a list :)

### CODE REVIEW

**Comment by igorpecovnik** [comment]
The case is, we don't have/keep older sources in the repository due to the size constrains. We will quickly ran out of space if we start sources for each update. A better solution of this problem is needed ... anyway nobody digs into some old sources.

**Comment by AristoChen** [comment]
I am not sure whether did I misunderstand what you mean,  but I'm not allowing user to download "each" version of kernel source, i used the shell command ```apt-cache --names-only search ^linux-source-* | awk '{ print $1 }' | grep -w ${BRANCH}-${LINUXFAMILY}``` to get a list.

in my cases,  I'm running on a ```4.19.57``` kernel version, and if i run the command above, i will get
```
linux-source-4.19.17-next-sunxi
linux-source-4.19.20-next-sunxi
linux-source-4.19.25-next-sunxi
linux-source-4.19.38-next-sunxi
linux-source-4.19.57-next-sunxi
linux-source-4.19.62-next-sunxi
```

User can only choose one of the above to install, maybe that wouldn't be too much?

I also agree that no one really dig into some old sources, maybe restrict the list to contain only equal version and newer version? if in my case, that will be like the following
```
linux-source-4.19.57-next-sunxi
linux-source-4.19.62-next-sunxi
```

**Comment by igorpecovnik** [comment]
> maybe restrict the list to contain only equal version and newer version?

"Newer version" is a bit odd - we expect people are at the latest. Perhaps showin last 5?

... and scripted install / uninstall must work the same way:

https://github.com/armbian/autotests/blob/master/tests/8500-install-kernel-sources.bash.disabled#L16-L17

Autotests are checking if sources for the latest update are present and alright. We need to keep that functionality.

**Comment by AristoChen** [comment]
Last 5 is ok for me :)

It seems that i have to modify both armbian/config and armbian/autotests to achieve what you expected, i will try to do that

**Comment by igorpecovnik** [comment]
Perhaps folowing the principle "pick the latest if none is selected" ?

**Comment by AristoChen** [comment]
I have only one H3 board, and selected the following version
```
linux-source-4.19.20-next-sunxi
linux-source-4.19.25-next-sunxi
linux-source-4.19.38-next-sunxi
linux-source-4.19.57-next-sunxi
linux-source-4.19.62-next-sunxi
```

everything is working as i expected, i will still try to figure out what goes wrong, maybe i will try to get a H6 board to test, i guess it might takes around a week to get one

If you have any suggestion or any idea, please let me know, thank you!

**Comment by igorpecovnik** [comment]
Can you start from a clean image from the download? We changed namings some time ago:

default -> legacy
next-> current
dev = dev

Kernels with "next" should not be shown at all, only "current", "legacy" and "dev".

 I will also do some more testings.

**Comment by AristoChen** [comment]
That was indeed a good suggestion, i think that i just reproduce the issue. I am currently running on on 5.4.20 kernel version, and if i select to install ```linux-source-5.4.20-current-sunxi```, i will get 5.4.18 just like what you got

But it seem that the problem is not about the code

I removed everything and clean them up, then directly run ```sudo apt-get install linux-source-5.4.20-current-sunxi```, i will still get 5.4.18

```
root@orangepipc:~# sudo apt-get install linux-source-5.4.20-current-sunxi
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  linux-source-5.4.20-current-sunxi
0 upgraded, 1 newly installed, 0 to remove and 38 not upgraded.
Need to get 392 MB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://apt.armbian.com buster/main armhf linux-source-5.4.20-current-sunxi all 5.4.20-current-sunxi+20.02.1 [392 MB]
Fetched 392 MB in 5min 48s (1,126 kB/s)
Selecting previously unselected package linux-source-5.4.20-current-sunxi.
(Reading database ... 34426 files and directories currently installed.)
Preparing to unpack .../linux-source-5.4.20-current-sunxi_5.4.20-current-sunxi+20.02.1_all.deb ...
Unpacking linux-source-5.4.20-current-sunxi (5.4.20-current-sunxi+20.02.1) ...
Setting up linux-source-5.4.20-current-sunxi (5.4.20-current-sunxi+20.02.1) ...
root@orangepipc:~# ls -l /usr/src
total 382400
-rw-rw-r-- 1 root root 391540512 Feb 17 01:05 linux-source-5.4.18-sunxi.tar.xz
-rw-rw-r-- 1 root root     36608 Feb 17 01:05 linux-sunxi-current_5.4.20_20.02.1_config.xz
```

btw, there is another problem with my code, i didn't know that "next " was not used anymore, so i will remove that from my code and push it later

**Comment by igorpecovnik** [comment]
Ahaa, but elsewhere ... good, then I will briefly test this once again and I think it can be merged.

**Comment by igorpecovnik** [comment]
We fixed the problem, but some older sources are just broken. I will purge old and broken from repository when I find time. This commit is good, merging.

**Pull request merged**
