### PR TITLE
Add submodule to select APT mirror from URL

### PR DESCRIPTION
**Pull request by tparys**
Possible patch to provide functionality requested in Issue #120.

Considered doing something more complicated given that there are mirrors listed for various regions.

However, there's currently only two unique mirrors, and "https://minio.k-space.ee/armbian/apt" is listed multiple times under "default".

So, doing the stupid simple thing for now.

### CODE REVIEW

**Comment by igorpecovnik** [comment]
> However, there's currently only two unique mirrors

That is correct. This is changing - when packages are pushed up, only primary mirrors are enabled until files are not reached around.

Thank you!

**Comment by igorpecovnik** [comment]
Tested, works.

Optional enhancements:
- possibility to set back to stock apt.armbian.com
- moving under "personal"
- echo is not noticed, perhaps just remove

**Comment by tparys** [comment]
As a thought, if things are still in flux, would it be better to use the apt mirror transport? And then just add something like this:

`deb mirror://apt.example.org/mirror.lst bullseye main`

Might be a more standard way of skinning that proverbial cat? I think apt will then auto-select the right mirror?

Failing that, if you have an idea of what the mirrors might look like in the future, might be something better to test with.

**Comment by tparys** [comment]
>     * moving under "personal"

Not sure I follow what you mean here.

**Comment by tparys** [comment]
> > ```
> > * moving under "personal"
> > ```
> 
> Not sure I follow what you mean here.

Nevermind. I think I see.

**Comment by igorpecovnik** [comment]
>  I think apt will then auto-select the right mirror?

Well, we already implemented [geo location based mirror selection](https://github.com/armbian/dl-router) so client based selector is not needed.

This whole functionality is a backup override if user prefers to fix it or in case system crashes. Hopefully this will not happen often.

**Comment by tparys** [comment]
Added another commit that should address your requests.

Noticed that https://apt.armbian.com/mirrors has changed. If you need more complicated functionality, let me know and I can take another crack at it?

**Comment by igorpecovnik** [comment]
>  If you need more complicated functionality, let me know and I can take another crack at it?

If you wanna play more, check API https://github.com/armbian/dl-router#api

Choosing regions? Like:
1. Default
2. Region 1
3. Region 2
4. ...
5. Fixed 1
6. Fixed 2

Perhaps this way?

**Comment by tparys** [comment]
Yeah. The expected interface is clear, but how to tackle it is not.

Ordinarily I'd break it up into a couple of functions, but debian-config-jobs is not set up that way. It's a 1600+ line bash function that looks like it needs some love.

I'll poke at it a bit, and push another commit if if it doesn't get too messy.

I may take a crack at reorganizing that if I get motivated. I've done something similar to generate dialog menus via a directory folder structure, and might be nicer to maintain longer term.

**Comment by tparys** [comment]
Minor cleanups, which I think does what you've requested given the documentation you pointed at.

I think it's working, but am having some IPv6 issues, so am getting intermittent results.

Let me know if it's working for you.

**Comment by igorpecovnik** [comment]
> Ordinarily I'd break it up into a couple of functions, but debian-config-jobs is not set up that way. It's a 1600+ line bash function that looks like it needs some love.

Agree. This armbian-config is 10+ years code which has origin in my private scripts for setting up some services. Things were just added without any serious RFC. This and lack of proper maintenance is the reasons it has been labelled as beta for years.

If you feel amused by seriously reworking armbian-config - you are more than welcome and we will support best way possible. When things start moving also more random help usually appears ..

> Let me know if it's working for you.

It does. I think all mirrors are ipv6 capable, but networking issues - which are outside our control - can appear. We are also working on a script that will regularly check mirror's health and remove/add broken ones as fast as possible.

**Comment by tparys** [comment]
> If you feel amused by seriously reworking armbian-config - you are more than welcome and we will support best way possible. When things start moving also more random help usually appears ..

I'll definitely take a crack at it sometime, but not on this pull request.

Think I'm going to need to do some more reading before I take a crack at a larger piece.

**Comment by igorpecovnik** [comment]
> I'll definitely take a crack at it sometime, but not on this pull request.

Sure, here functionality is covered so I guess we can merge this in.

> Think I'm going to need to do some more reading before I take a crack at a larger piece.

Probably best is to make a design and break into smaller chunks. We use https://armbian.atlassian.net/ for managing / have some control over development. Without access its read only. Send me email for access.

**Pull request merged**
